spring:
  datasource:
    url: "jdbc:mysql://localhost:3306/library"
    username: "root"
    password: "@Blessing22#"

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect

server:
  port: 8081